organization := "com.github.gphat"

name := "wabisabi"

scalaVersion := "2.12.1"

crossScalaVersions := Seq("2.11.8", "2.12.1")

scalacOptions ++= Seq("-unchecked", "-deprecation", "-feature", "-Yrangepos")

resolvers += "Scalaz Bintray Repo" at "http://dl.bintray.com/scalaz/releases"

libraryDependencies ++= Seq(
  "net.databinder.dispatch" %% "dispatch-core"  % "0.12.0",
  "org.clapper"       %% "grizzled-slf4j"       % "1.3.0",
  "com.netaporter"    %% "scala-uri"            % "0.4.16",
  "org.specs2"        %% "specs2-core"          % "3.8.9"   % "test",
  "org.specs2"        %% "specs2-matcher-extra" % "3.8.9"   % "test",
  "org.slf4j"         % "slf4j-simple"          % "1.7.9"   % "test",
  "org.elasticsearch" % "elasticsearch"         % "5.2.2"   % "test",
  "org.apache.logging.log4j" % "log4j-api"      % "2.8.1"   % "test",
  "io.argonaut"       %% "argonaut"             % "6.2-RC2" % "test"
)

// This is intended to remove the noise generated by loads of log entries outputted to console
// by Elasticsearch embedded server when running the tests
testOptions in Test ++= Seq(
  Tests.Setup( () => System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "warn"))
)

releasePublishArtifactsAction := PgpKeys.publishSigned.value

releaseCrossBuild := true

Publish.settings
