organization := "wabisabi"

name := "wabisabi"

version := "2.0.15"

scalaVersion := "2.11.5"

crossScalaVersions := Seq("2.10.4")

scalacOptions ++= Seq("-unchecked", "-deprecation", "-feature")

libraryDependencies += "net.databinder.dispatch" %% "dispatch-core" % "0.11.2"

libraryDependencies += "org.clapper" %% "grizzled-slf4j" % "1.0.2"

libraryDependencies += "org.specs2" %% "specs2" % "2.4.15" % "test"

libraryDependencies += "org.slf4j" % "slf4j-simple" % "1.7.9" % "test"

libraryDependencies += "com.netaporter" %% "scala-uri" % "0.4.3"

libraryDependencies += "org.elasticsearch" % "elasticsearch" % "1.4.2" % "test"

// This is intended to remove the noise generated by loads of log entries outputted to console
// by Elasticsearch embedded server when running the tests
testOptions in Test ++= Seq(
  Tests.Setup( () => System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "warn"))
)

publishTo := Some(Resolver.file("file",  new File( "/Users/gphat/src/mvn-repo/releases" )) )


